"""Alembic environment.

Migrations run as ``platform_owner`` — the only place that role is used. The
application never holds it, because it is a superuser and would bypass every
row-level security policy these migrations create.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from platform_core.db.models import Base
from platform_core.settings import get_settings

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The one place the owner DSN is read. Sourced from validated settings rather
# than alembic.ini so the migration path cannot drift from the runtime config.
config.set_main_option("sqlalchemy.url", str(get_settings().database_owner_url))

target_metadata = Base.metadata


def _include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep autogenerate away from things it cannot see.

    Policies, grants and RLS flags are invisible to Alembic's comparison, so an
    autogenerated migration would happily drop a table and recreate it without
    them. Extensions are managed by the container's init script.
    """
    return not (type_ == "table" and name == "pg_stat_statements")


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=_include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=_include_object,
            compare_type=True,
            # Every migration runs in one transaction so a failure leaves no
            # half-applied schema. Postgres supports transactional DDL; using it
            # is what makes "reversible" more than a hope.
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
